<h3>New pokemon</h3>

<?php
  $form = $this->form;
  $form->prepare();
  echo $this->form()->openTag($form); // <form method="POST">
?>
<div class="form-group">
  <?php echo $this->formRow($form->get('id_national')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('typeA')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('typeB')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('parent_id')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('description')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag();  // </form> ?>
