<?php
$form = $this->form;
$form->prepare();
?>
<h1>Edit pokemon</h1>

<?php echo $this->form()->openTag($form); // <form action...> ?>

<div class="form-group">
  <?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('typeA')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('typeB')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('parent_id')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('description')); ?>
</div>
<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); // </form> ?>
