<div>
  <h3>My Pokedex</h3>
  <?php if($this->identity()){ ?>
  <a class="btn btn-primary" href="<?php echo $this->url("pokedex_add"); ?>">Add a new pokemon</a>
  <?php } ?>
</div>
<br><br>
<?php if (!empty($this->pokemons)) : ?>
<div id="pokemons">
    <?php foreach ($this->pokemons as $pokemon) : ?>
          <div class="col-md-3">
            <div class="header-box">
              <?php 
                $idNational = $pokemon->getIdNational();
                if ($idNational < 10)
                  echo '#00'.$this->escapeHtml($idNational);
                elseif ($idNational > 9 && $idNational < 100)
                  echo '#0'.$this->escapeHtml($idNational);
                else
                  echo '#'. $this->escapeHtml($idNational);
              ?>
              <strong>
                  <a href="<?php echo $this->url(
                    'display_pokemon', [
                      'pokemonSlug' => $pokemon->getName()
                    ]); ?>">
                    <?php echo $this->escapeHtml($pokemon->getName()); ?>
                  </a>
              </strong>
            </div>
            <div class="images">
              <img src="/img/icone/<?php echo $pokemon->getIdNational(); ?>.png">
              <img src="/img/icone_shiny/<?php echo $pokemon->getIdNational(); ?>.png">
            </div>
            <div class="types">
              <div class="col-md-2 <?php echo $pokemon->getTypeA(); ?>">
                <?php echo $this->escapeHtml($pokemon->getTypeA()); ?>
              </div>
              
              <?php
                $typeB = $pokemon->getTypeB();
                if ($typeB != null || $typeB != ''){
                  ?>
                <div class="col-md-2 <?php echo $pokemon->getTypeB(); ?>">
                  <?php echo $this->escapeHtml($typeB); ?>
                </div>
              <?php } ?>
            </div>
              
          </div>
    <?php endforeach; ?>
    </div>
<?php else : ?>
    <div>Nothing to display</div>
<?php endif; ?>
<div class="pagination">
  <?php
      echo $this->paginationControl(
        $this->pokemons,
        'Sliding',
        'partial/pagination',
        ['route' => 'pokedex_home/paged']
      );
  ?>
</div>

