<?php
$pokemon = $this->pokemon;

?>
<h1><?php echo $this->escapeHtml($pokemon->getName()); ?></h1>
<?php if($this->identity()){ ?>
<a class="btn btn-primary" href="<?php echo $this->url('edit_pokemon', ['pokemonId' => $pokemon->getId()]); ?>">
  <i class="glyphicon glyphicon-pencil"></i> Edit
</a>
<a class="btn btn-danger" href="<?php echo $this->url('delete_pokemon', ['pokemonId' => $pokemon->getId()]) ;?>">
  <i class="glyphicon glyphicon-remove"></i> Delete
</a>
<?php } ?>
<hr />
<div class="col-md-3">
  <img src="/img/sprites/<?php echo $pokemon->getIdNational(); ?>.gif">
</div>
  <div class="col-md-9">
  <!-- ID National -->
  <div class="header">
    <?php 
      $idNational = $pokemon->getIdNational();
      if ($idNational < 10)
        echo '#00'.$this->escapeHtml($idNational);
      elseif ($idNational > 9 && $idNational < 100)
        echo '#0'.$this->escapeHtml($idNational);
      else
        echo '#'. $this->escapeHtml($idNational);
    ?>
    <?php echo nl2br($this->escapeHtml($pokemon->getName())); ?>
  </div>
  <div class="types">
    <div class="col-md-2 <?php echo $pokemon->getTypeA(); ?>">
      <?php echo nl2br($this->escapeHtml($pokemon->getTypeA())); ?>
    </div>
    <?php
      $typeB = $pokemon->getTypeB();
      if ($typeB != null || $typeB != '') {
      ?>
      <div class="col-md-2 <?php echo $pokemon->getTypeB(); ?>">
        <?php
          echo $this->escapeHtml($typeB);
        ?>
      </div>
      <?php
      }
    ?>
  </div>
  <br>
  <div class="description">
    <?php echo nl2br($this->escapeHtml($pokemon->getDescription())); ?>
  </div>
    <!-- récupérer les évolutions -->
    <h4 class="evolutions">Evolutions :</h4>
    <?php if ($evolution != null){ ?>
      <strong>
        <a href="<?php echo $this->url(
          'display_pokemon', [
            'pokemonSlug' => $evolution->getName()
          ]); ?>">
          <?php echo $this->escapeHtml($evolution->getName()); ?>
        </a>
      </strong>
    <?php
      if($evolutionB != null) {
        echo ', ';
    ?>
      <strong>
        <a href="<?php echo $this->url(
          'display_pokemon', [
            'pokemonSlug' => $evolutionB->getName()
          ]); ?>">
          <?php echo $this->escapeHtml($evolutionB->getName()); ?>
        </a>
      </strong>
    <?php
      }
    } else
      echo 'aucune évolution pour ce pokemon.';
    ?>
  </div>
</div>
<br />