<?php
$pokemon = $this->pokemon;

?>
<h1><?php echo $this->escapeHtml($pokemon->getName()); ?></h1>
<a class="btn btn-primary" href="<?php echo $this->url('edit_pokemon', ['pokemonId' => $pokemon->getId()]); ?>">
  <i class="glyphicon glyphicon-pencil"></i> Edit
</a>
<a class="btn btn-danger" href="<?php echo $this->url('delete_pokemon', ['pokemonId' => $pokemon->getId()]) ;?>">
  <i class="glyphicon glyphicon-remove"></i> Delete
</a>
<hr />
<div class="row">
  <div class="col-md-12">
    <?php echo nl2br($this->escapeHtml($pokemon->getDescription())); ?>
  </div>
</div>
<br />