-- MySQL Script generated by MySQL Workbench
-- 02/28/17 14:45:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MyPokedex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyPokedex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyPokedex` DEFAULT CHARACTER SET utf8 ;
USE `MyPokedex` ;

-- -----------------------------------------------------
-- Table `MyPokedex`.`Pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyPokedex`.`Pokemon` ;

CREATE TABLE IF NOT EXISTS `MyPokedex`.`Pokemon` (
  `Id_Pokemon` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type1` VARCHAR(45) NOT NULL,
  `Type2` VARCHAR(45) NULL,
  `Parent_id` INT NULL,
  `Description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Id_Pokemon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPokedex`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyPokedex`.`User` ;

CREATE TABLE IF NOT EXISTS `MyPokedex`.`User` (
  `Id_user` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyPokedex`.`LastSeen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyPokedex`.`LastSeen` ;

CREATE TABLE IF NOT EXISTS `MyPokedex`.`LastSeen` (
  `Id_lastSeen` INT NOT NULL AUTO_INCREMENT,
  `Latitude` FLOAT NOT NULL,
  `Longitude` FLOAT NOT NULL,
  `Pokemon_Id_Pokemon` INT NOT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`Id_lastSeen`, `Pokemon_Id_Pokemon`),
  INDEX `fk_Last_seen_Pokemon_idx` (`Pokemon_Id_Pokemon` ASC),
  CONSTRAINT `fk_Last_seen_Pokemon`
    FOREIGN KEY (`Pokemon_Id_Pokemon`)
    REFERENCES `MyPokedex`.`Pokemon` (`Id_Pokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
